<?xml version="1.0" encoding="UTF-8"?>
<project name="ProyectoPasteleria" default="default" basedir=".">
    <description>Builds, tests, and runs the project ProyectoPasteleria.</description>
    <import file="nbproject/build-impl.xml"/>
    
    <!-- ========================================== -->
    <!-- CONFIGURACIÓN DE JACOCO (CODE COVERAGE)     -->
    <!-- ========================================== -->
    <property name="jacoco.dir" location="lib"/>
    <taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
        <classpath path="${jacoco.dir}/jacocoant.jar"/>
    </taskdef>

    <target name="generar-reporte-cobertura" depends="compile, compile-test" description="Genera el reporte automatico de Code Coverage con JaCoCo">
        <!-- 1. Ejecuta las pruebas unitarias instrumentadas con JaCoCo -->
        <jacoco:coverage destfile="${basedir}/build/jacoco.exec" xmlns:jacoco="antlib:org.jacoco.ant">
            <junit printsummary="yes" haltonfailure="no" fork="yes" showoutput="true">
                <classpath>
                    <path path="${build.classes.dir}"/>
                    <path path="${build.test.classes.dir}"/>
                    <fileset dir="${basedir}/lib">
                        <include name="*.jar"/>
                    </fileset>
                </classpath>
                <batchtest fork="yes">
                    <fileset dir="${build.test.classes.dir}">
                        <include name="**/*Test.class"/>
                    </fileset>
                </batchtest>
            </junit>
        </jacoco:coverage>
        
        <!-- 2. Genera el informe visual en HTML -->
        <jacoco:report xmlns:jacoco="antlib:org.jacoco.ant">
            <executiondata>
                <file file="${basedir}/build/jacoco.exec"/>
            </executiondata>
            <structure name="ProyectoPasteleria Coverage">
                <classfiles>
                    <fileset dir="${build.classes.dir}"/>
                </classfiles>
                <sourcefiles encoding="UTF-8">
                    <fileset dir="${basedir}/src"/>
                </sourcefiles>
            </structure>
            <html destdir="${basedir}/reporte-cobertura"/>
        </jacoco:report>
        <echo message="EXITO: El reporte de Code Coverage se ha creado en la carpeta reporte-cobertura/index.html" />
    </target>
</project>