/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Clases.Ingrediente;
import Modelo.Clases.Sesion;
import Modelo.ConexionBD;
import Modelo.DAO.DepartamentoDAO;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import Modelo.DAO.IngredienteDAO;
import Modelo.DAO.MedidasIngredientesDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ingri
 */
public class FrmInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInventario.class.getName());

    
    public void limpiar(){

    txtIdIngrediente.setText("");

    txtNombreIngrediente.setText("");

    txtCantidadIngrediente.setText("");

    JcomboMedidasIngredientes.setSelectedIndex(0);

    txtPrecioUnitario.setText("");

    }
    /**
     * Creates new form FrmInventario
     */
    public FrmInventario() {
        initComponents();
        setLocationRelativeTo(null);

        setTitle("Gestión de Inventario");
        
        IngredienteDAO dao = new IngredienteDAO();
        dao.mostrarIngredientes(tblIngredientes);
        
        MedidasIngredientesDAO daoMedidas = new MedidasIngredientesDAO();
        daoMedidas.mostrarMedidasIngredientes(JcomboMedidasIngredientes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdIngrediente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreIngrediente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GuardarIngrediente = new javax.swing.JButton();
        EditarIngrediente = new javax.swing.JButton();
        EliminarIngrediente = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        JcomboMedidasIngredientes = new javax.swing.JComboBox<>();
        txtPrecioUnitario = new javax.swing.JTextField();
        txtCantidadIngrediente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngredientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BtnTarjetaTiempo = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        HojaCostos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 242, 242));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Inventario de Ingredientes");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Datos del ingrediente");

        jLabel3.setText("ID ingrediente:");

        txtIdIngrediente.setEnabled(false);

        jLabel4.setText("Nombre:");

        jLabel5.setText("Cantidad");

        jLabel6.setText("Medida:");

        jLabel7.setText("Precio Unitario:");

        GuardarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GuardarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/guardar.png"))); // NOI18N
        GuardarIngrediente.setText("Guardar");
        GuardarIngrediente.addActionListener(this::btnGuardarIngredienteActionPerformed);

        EditarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/editar.png"))); // NOI18N
        EditarIngrediente.setText("Editar");
        EditarIngrediente.addActionListener(this::btnEditarActionPerformed);

        EliminarIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EliminarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/borrar.png"))); // NOI18N
        EliminarIngrediente.setText("Eliminar");
        EliminarIngrediente.addActionListener(this::EliminarIngredienteActionPerformed);

        ButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/limpiar.png"))); // NOI18N
        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.addActionListener(this::ButtonLimpiarIngredienteActionPerformed);

        JcomboMedidasIngredientes.addActionListener(this::JcomboMedidasIngredientesActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(GuardarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(EditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIdIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(JcomboMedidasIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcomboMedidasIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Lista de Ingredientes");

        tblIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Ingrediente", "Nombre", "Cantidad", "Unidad de Medida", "Precio Unitario", "Precio Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngredientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngredientes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(252, 227, 227));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inicio.png"))); // NOI18N
        jButton1.setText("  Inicio");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(this::jButton1MenuInicioButton);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/empleados.png"))); // NOI18N
        jButton2.setText("Empleados");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(this::jButton2jButtonEmpleados);

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario (1).png"))); // NOI18N
        jButton3.setText("Inventario");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(this::jButton3jButtonInventario);

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario.png"))); // NOI18N
        jButton4.setText("Productos");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(this::jButton4jButtonProductos);

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/masa.png"))); // NOI18N
        jButton5.setText("Producción");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(this::jButton5jButtonProduccion);

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/requisicion.png"))); // NOI18N
        jButton6.setText("Requisiciones");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(this::jButton6jButtonRequisiciones);

        BtnTarjetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BtnTarjetaTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        BtnTarjetaTiempo.setText("Tarjeta Tiempo");
        BtnTarjetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnTarjetaTiempo.addActionListener(this::BtnTarjetaTiempojButtonReporte);

        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar-sesion.png"))); // NOI18N
        jButton8.setText("Cerrar Sesión");
        jButton8.addActionListener(this::jButton8jButtonCerrarSesion);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/LogoCorrecto.png"))); // NOI18N

        HojaCostos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HojaCostos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        HojaCostos.setText("Hoja Costos");
        HojaCostos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HojaCostos.addActionListener(this::HojaCostosjButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnGuardarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarIngredienteActionPerformed
        // TODO add your handling code here:
        Ingrediente ing = new Ingrediente();

        // Obtener datos de los JTextField
        ing.setNombreIngrediente(txtNombreIngrediente.getText());

        try {
            ing.setCantidad(Integer.parseInt(txtCantidadIngrediente.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Ingrese una cantidad válida");
        }

        String medida = JcomboMedidasIngredientes.getSelectedItem().toString();
        ing.setMedida(medida);

        try {
            ing.setPrecioUnitario(Integer.parseInt(txtPrecioUnitario.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Ingrese una cantidad válida");
        }

        // Crear DAO
        IngredienteDAO dao = new IngredienteDAO();

        // Guardar
        boolean respuesta = dao.guardarIngrediente(ing);

            if(respuesta){

                JOptionPane.showMessageDialog(this,
                    "Ingrediente guardado correctamente");

            }else{

                JOptionPane.showMessageDialog(this,
                    "Error al guardar");

            }
            //RECARGAR TABLA
            dao.mostrarIngredientes(tblIngredientes);

            //LIMPIAR CAMPOS
            limpiar();
    }//GEN-LAST:event_btnGuardarIngredienteActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(txtIdIngrediente.getText().equals("")){

            JOptionPane.showMessageDialog(this,
                    "Selecciona un empleado");

            return;

        }
        Ingrediente ing = new Ingrediente();

        ing.setIdIngrediente(
            Integer.parseInt(txtIdIngrediente.getText())
        );

        ing.setNombreIngrediente(txtNombreIngrediente.getText());

        ing.setCantidad(
            Integer.parseInt(txtCantidadIngrediente.getText())
        );

        //Guarda el texto seleccionado en el combobox medidaIngrediente
        String medida = JcomboMedidasIngredientes.getSelectedItem().toString();
        ing.setMedida(medida);
        
        ing.setPrecioUnitario(
            Double.parseDouble(txtPrecioUnitario.getText())
        );

        IngredienteDAO dao = new IngredienteDAO();

        boolean respuesta = dao.editarIngrediente(ing);

        if(respuesta){

            JOptionPane.showMessageDialog(this,
                    "Ingrediente actualizado");

            dao.mostrarIngredientes(tblIngredientes);

        }else{

            JOptionPane.showMessageDialog(this,
                    "Error al actualizar");

        }
        limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void EliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarIngredienteActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Deseas eliminar este ingrediente?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION){

            int id = Integer.parseInt(
                    txtIdIngrediente.getText());

            IngredienteDAO dao = new IngredienteDAO();

            boolean respuesta = dao.eliminarIngrediente(id);

            if(respuesta){

                JOptionPane.showMessageDialog(this,
                        "Empleado eliminado");

                dao.mostrarIngredientes(tblIngredientes);

            }else{

                JOptionPane.showMessageDialog(this,
                        "Error al eliminar");

            }

        }
        limpiar();
    }//GEN-LAST:event_EliminarIngredienteActionPerformed

    private void ButtonLimpiarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarIngredienteActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_ButtonLimpiarIngredienteActionPerformed

    private void tblIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngredientesMouseClicked
        // TODO add your handling code here:
        int fila = tblIngredientes.getSelectedRow();

        if(fila >= 0){

            txtIdIngrediente.setText(
                tblIngredientes.getValueAt(fila, 0).toString()
            );

            txtNombreIngrediente.setText(
                tblIngredientes.getValueAt(fila, 1).toString()
            );

            txtCantidadIngrediente.setText(
              tblIngredientes.getValueAt(fila, 2).toString()
            );

            JcomboMedidasIngredientes.setSelectedItem(
                tblIngredientes.getValueAt(fila, 3).toString());
            }
            txtPrecioUnitario.setText(
                tblIngredientes.getValueAt(fila, 4).toString()
            );
    }//GEN-LAST:event_tblIngredientesMouseClicked

    private void JcomboMedidasIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboMedidasIngredientesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JcomboMedidasIngredientesActionPerformed

    private void jButton1MenuInicioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MenuInicioButton
        // TODO add your handling code here:
        FrmMenuInicio menuInicio = new FrmMenuInicio();
        menuInicio.setVisible(true);
    }//GEN-LAST:event_jButton1MenuInicioButton

    private void jButton2jButtonEmpleados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButtonEmpleados
        // TODO add your handling code here:
        if(Sesion.idDepartamento != 4){

            JOptionPane.showMessageDialog(
                    this,
                    "Solo el departamento Administrador puede acceder al módulo de empleados.");

            return;

        }

        FrmEmpleado frm =
                new FrmEmpleado();

        frm.setVisible(true);
    }//GEN-LAST:event_jButton2jButtonEmpleados

    private void jButton3jButtonInventario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButtonInventario
        // TODO add your handling code here:
        FrmInventario inventario = new FrmInventario();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3jButtonInventario

    private void jButton4jButtonProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButtonProductos
        // TODO add your handling code here:
        FrmProducto producto = new FrmProducto();
        producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4jButtonProductos

    private void jButton5jButtonProduccion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5jButtonProduccion
        // TODO add your handling code here:
        FrmProduccion produccion = new FrmProduccion();
        produccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5jButtonProduccion

    private void jButton6jButtonRequisiciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6jButtonRequisiciones
        // TODO add your handling code here:
        FrmRequisicion req = new FrmRequisicion();
        req.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6jButtonRequisiciones

    private void BtnTarjetaTiempojButtonReporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTarjetaTiempojButtonReporte
        // TODO add your handling code here:
        FrmTarjetaTiempo tarjeta = new FrmTarjetaTiempo();
        tarjeta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTarjetaTiempojButtonReporte

    private void jButton8jButtonCerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButtonCerrarSesion
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estas seguro de Cerrar Sesión?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION){

            FrmLogin login = new FrmLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8jButtonCerrarSesion

    private void HojaCostosjButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HojaCostosjButton
        // TODO add your handling code here:
        FrmHojaCostos hojaCostos = new FrmHojaCostos();
        hojaCostos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HojaCostosjButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInventario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTarjetaTiempo;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton EditarIngrediente;
    private javax.swing.JButton EliminarIngrediente;
    private javax.swing.JButton GuardarIngrediente;
    private javax.swing.JButton HojaCostos;
    private javax.swing.JComboBox<String> JcomboMedidasIngredientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIngredientes;
    private javax.swing.JTextField txtCantidadIngrediente;
    private javax.swing.JTextField txtIdIngrediente;
    private javax.swing.JTextField txtNombreIngrediente;
    private javax.swing.JTextField txtPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
