/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Clases.Producto;
import Modelo.Clases.Sesion;
import Modelo.DAO.CategoriaProductoDAO;
import Modelo.DAO.EstadoProductoDAO;
import Modelo.DAO.ProductoDAO;
import Modelo.DAO.TamanoProductoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author ingri
 */
public class FrmProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProducto.class.getName());

    /**
     * Creates new form FrmProducto
     */
    public FrmProducto() {
        initComponents();
        
        setLocationRelativeTo(null);

        setTitle("Gestión de Productos");
        
        ProductoDAO daoProducto = new ProductoDAO();
        daoProducto.mostrarProductos(tblProducto);
        
        CategoriaProductoDAO daoCategoria = new CategoriaProductoDAO();
        daoCategoria.mostrarMedidasIngredientes(cmbCategoria);
        
        EstadoProductoDAO daoEstado = new EstadoProductoDAO();
        daoEstado.mostrarEstadoProducto(cmbEstado);
        
        TamanoProductoDAO daoTamano = new TamanoProductoDAO();
        daoTamano.mostrarTamanoProducto(cmbTamano);
    }
    
    public void limpiar(){

    txtIdProducto.setText("");

    txtNombreProducto.setText("");

    cmbCategoria.setSelectedIndex(0);

    txtDescripcion.setText("");

    cmbEstado.setSelectedIndex(0);
    
    txtPrecioVenta.setText("");

    cmbTamano.setSelectedIndex(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        buttonEditarActionPerformed = new javax.swing.JButton();
        ButtonEliminarActionPerformed = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTamano = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BtnTarjetaTiempo = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        HojaCostos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(248, 242, 242));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel1.setText("Gestión de Productos");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Datos del producto");

        jLabel3.setText("ID producto:");

        txtIdProducto.setEnabled(false);

        jLabel4.setText("Nombre del producto:");

        jLabel5.setText("Categoría:");

        jLabel6.setText("Descripción:");

        jLabel7.setText("Precio de venta:");

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/guardar.png"))); // NOI18N
        jButton17.setText("Guardar");
        jButton17.addActionListener(this::jButtonGuardarProducto);

        buttonEditarActionPerformed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonEditarActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/editar.png"))); // NOI18N
        buttonEditarActionPerformed.setText("Editar");
        buttonEditarActionPerformed.addActionListener(this::buttonEditarActionPerformedActionPerformed);

        ButtonEliminarActionPerformed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEliminarActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/borrar.png"))); // NOI18N
        ButtonEliminarActionPerformed.setText("Eliminar");
        ButtonEliminarActionPerformed.addActionListener(this::ButtonEliminarActionPerformedActionPerformed);

        ButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/limpiar.png"))); // NOI18N
        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.addActionListener(this::ButtonLimpiarActionPerformed);

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        jLabel8.setText("Tamaño:");

        cmbTamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel10.setText("Estado:");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(buttonEditarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(ButtonEliminarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(268, 268, 268)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonEditarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonEliminarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Lista de Productos");

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Nombre del producto", "Categoría", "Tamaño", "Precio de Venta", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(252, 227, 227));

        jButton11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inicio.png"))); // NOI18N
        jButton11.setText("  Inicio");
        jButton11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton11.addActionListener(this::jButton11MenuInicioButton);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/empleados.png"))); // NOI18N
        jButton2.setText("Empleados");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(this::jButton2jButtonEmpleados);

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario (1).png"))); // NOI18N
        jButton3.setText("Inventario");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(this::jButton3jButtonInventario);

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario.png"))); // NOI18N
        jButton4.setText("Productos");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(this::jButton4jButtonProductos);

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/masa.png"))); // NOI18N
        jButton5.setText("Producción");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(this::jButton5jButtonProduccion);

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/requisicion.png"))); // NOI18N
        jButton6.setText("Requisiciones");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(this::jButton6jButtonRequisiciones);

        BtnTarjetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BtnTarjetaTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        BtnTarjetaTiempo.setText("Tarjeta Tiempo");
        BtnTarjetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnTarjetaTiempo.addActionListener(this::BtnTarjetaTiempojButtonReporte);

        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar-sesion.png"))); // NOI18N
        jButton8.setText("Cerrar Sesión");
        jButton8.addActionListener(this::jButton8jButtonCerrarSesion);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/LogoCorrecto.png"))); // NOI18N

        HojaCostos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HojaCostos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        HojaCostos.setText("Hoja Costos");
        HojaCostos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HojaCostos.addActionListener(this::HojaCostosjButton);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarProducto
        // TODO add your handling code here:
        
        if(txtNombreProducto.getText().equals("") ||
            txtPrecioVenta.getText().equals("")){

            JOptionPane.showMessageDialog(this,
                 "Complete los campos obligatorios");

            return;
         }
        // Crear objeto Producto
        Producto prod = new Producto();

        prod.setNombreProducto(
                txtNombreProducto.getText());

        // Categoría
        String categoriaSeleccionada =
                cmbCategoria.getSelectedItem().toString();

        CategoriaProductoDAO catDAO =
                new CategoriaProductoDAO();

        prod.setIdCategoria(
                catDAO.obtenerIdCategoria(
                        categoriaSeleccionada));

        // Tamaño
        prod.setTamano(
                cmbTamano.getSelectedItem().toString());

        // Descripción
        prod.setDescripcion(
                txtDescripcion.getText());

        // Precio
        prod.setPrecioVenta(
                Double.parseDouble(
                        txtPrecioVenta.getText()));

        // Estado
        String estadoSeleccionado =
                cmbEstado.getSelectedItem().toString();

        EstadoProductoDAO estDAO =
                new EstadoProductoDAO();

        prod.setIdEstadoProducto(
                estDAO.obtenerIdEstado(
                        estadoSeleccionado));

        // Guardar
        ProductoDAO dao = new ProductoDAO();

        dao.guardarProducto(prod);
        
         dao.mostrarProductos(tblProducto);
        
        //Limpiar campos
        limpiar();
    }//GEN-LAST:event_jButtonGuardarProducto

    private void buttonEditarActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformedActionPerformed
        // TODO add your handling code here:
        if(txtIdProducto.getText().equals("")){

            JOptionPane.showMessageDialog(this,
                    "Selecciona un empleado");

            return;

        }
        Producto prod = new Producto();

        prod.setIdProducto(
            Integer.parseInt(txtIdProducto.getText())
        );

        prod.setNombreProducto(txtNombreProducto.getText());

        int idCategoria =
                cmbCategoria.getSelectedIndex();
        prod.setIdCategoria(idCategoria);

        prod.setDescripcion(txtDescripcion.getText());

        int idEstado =
            cmbEstado.getSelectedIndex();

        prod.setIdEstadoProducto(idEstado);

        prod.setPrecioVenta(
                Double.parseDouble(txtPrecioVenta.getText()));
        
        prod.setTamano(
            cmbTamano.getSelectedItem().toString()
        );

        ProductoDAO dao = new ProductoDAO();

        boolean respuesta = dao.editarProducto(prod);

        if(respuesta){

            JOptionPane.showMessageDialog(this,
                    "Producto actualizado");

            dao.mostrarProductos(tblProducto);

        }else{

            JOptionPane.showMessageDialog(this,
                    "Error al actualizar");

        }
        limpiar();
    }//GEN-LAST:event_buttonEditarActionPerformedActionPerformed

    private void ButtonEliminarActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformedActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Deseas eliminar este producto?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION){

            int id = Integer.parseInt(
                    txtIdProducto.getText());

            ProductoDAO dao = new ProductoDAO();

            boolean respuesta = dao.eliminarProducto(id);

            if(respuesta){

                JOptionPane.showMessageDialog(this,
                        "Producto eliminado");

                dao.mostrarProductos(tblProducto);

            }else{

                JOptionPane.showMessageDialog(this,
                        "Error al eliminar");

            }

        }
        limpiar();
    }//GEN-LAST:event_ButtonEliminarActionPerformedActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        // TODO add your handling code here:
        int fila = tblProducto.getSelectedRow();

        if(fila >= 0){

            txtIdProducto.setText(
                tblProducto.getValueAt(fila, 0).toString()
            );

            txtNombreProducto.setText(
                tblProducto.getValueAt(fila, 1).toString()
            );
            
            cmbCategoria.setSelectedItem(
                tblProducto.getValueAt(fila, 2).toString()
            );
            
            cmbTamano.setSelectedItem(
                tblProducto.getValueAt(fila, 3).toString()
            );
             
            txtDescripcion.setText(
                tblProducto.getValueAt(fila, 4).toString()
            );
            
            txtPrecioVenta.setText(
                tblProducto.getValueAt(fila, 5).toString()
            );
            
            cmbEstado.setSelectedItem(
                tblProducto.getValueAt(fila, 6).toString()
            );
        }
    }//GEN-LAST:event_tblProductoMouseClicked

    private void jButton11MenuInicioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11MenuInicioButton
        // TODO add your handling code here:
        FrmMenuInicio menuInicio = new FrmMenuInicio();
        menuInicio.setVisible(true);
    }//GEN-LAST:event_jButton11MenuInicioButton

    private void jButton2jButtonEmpleados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButtonEmpleados
        // TODO add your handling code here:
        if(Sesion.idDepartamento != 4){

            JOptionPane.showMessageDialog(
                    this,
                    "Solo el departamento Administrador puede acceder al módulo de empleados.");

            return;

        }

        FrmEmpleado frm =
                new FrmEmpleado();

        frm.setVisible(true);
    }//GEN-LAST:event_jButton2jButtonEmpleados

    private void jButton3jButtonInventario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButtonInventario
        // TODO add your handling code here:
        FrmInventario inventario = new FrmInventario();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3jButtonInventario

    private void jButton4jButtonProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButtonProductos
        // TODO add your handling code here:
        FrmProducto producto = new FrmProducto();
        producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4jButtonProductos

    private void jButton5jButtonProduccion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5jButtonProduccion
        // TODO add your handling code here:
        FrmProduccion produccion = new FrmProduccion();
        produccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5jButtonProduccion

    private void jButton6jButtonRequisiciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6jButtonRequisiciones
        // TODO add your handling code here:
        FrmRequisicion req = new FrmRequisicion();
        req.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6jButtonRequisiciones

    private void BtnTarjetaTiempojButtonReporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTarjetaTiempojButtonReporte
        // TODO add your handling code here:
        FrmTarjetaTiempo tarjeta = new FrmTarjetaTiempo();
        tarjeta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTarjetaTiempojButtonReporte

    private void jButton8jButtonCerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButtonCerrarSesion
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estas seguro de Cerrar Sesión?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION){

            FrmLogin login = new FrmLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8jButtonCerrarSesion

    private void HojaCostosjButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HojaCostosjButton
        // TODO add your handling code here:
        FrmHojaCostos hojaCostos = new FrmHojaCostos();
        hojaCostos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HojaCostosjButton



    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTarjetaTiempo;
    private javax.swing.JButton ButtonEliminarActionPerformed;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton HojaCostos;
    private javax.swing.JButton buttonEditarActionPerformed;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTamano;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
