/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Clases.Requisicion;
import Modelo.Clases.Sesion;
import Modelo.DAO.ProduccionDAO;
import Modelo.DAO.RequisicionDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ingri
 */
public class FrmRequisicion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRequisicion.class.getName());

    /**
     * Creates new form FrmRequisicion
     */
    public FrmRequisicion() {
        initComponents();
        
        setLocationRelativeTo(null);

        setTitle("Requisiciones");
        
        ProduccionDAO dao = new ProduccionDAO();
        dao.llenarComboPedidos(cmbNoPedidos);
        
        RequisicionDAO daoRequisicion = new RequisicionDAO();
        daoRequisicion.llenarDepartamentos(cmbDepartamento);
        daoRequisicion.mostrarRequisiciones(tblRequisiciones);
    }
    
    public void limpiar(){
        txtFechaReq.setText("");

        cmbDepartamento.setSelectedIndex(0);

        cmbSolicitante.removeAllItems();

        cmbNoPedidos.setSelectedIndex(0);

        txtObservaciones.setText("");

        txtEntrega.setText("");

        txtRecibido.setText("");

        txtTotalReq.setText("");

        DefaultTableModel modelo =
                (DefaultTableModel)
                tblMaterialesSolicitados.getModel();

        modelo.setRowCount(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        BtnTarjetaTiempo = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        HojaCostos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNoRequisicion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaReq = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbDepartamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        cmbNoPedidos = new javax.swing.JComboBox<>();
        cmbSolicitante = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMaterialesSolicitados = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtTotalReq = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtEntrega = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtRecibido = new javax.swing.JTextField();
        buttonGenerarReqActionPerformed = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblRequisiciones = new javax.swing.JTable();
        ImprimirReq = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        ButtonEliminarActionPerformed = new javax.swing.JButton();
        ButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 227, 227));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inicio.png"))); // NOI18N
        jButton1.setText("  Inicio");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(this::jButton1MenuInicioButton);

        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/empleados.png"))); // NOI18N
        jButton2.setText("Empleados");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(this::jButton2jButtonEmpleados);

        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario (1).png"))); // NOI18N
        jButton3.setText("Inventario");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(this::jButton3jButtonInventario);

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/inventario.png"))); // NOI18N
        jButton4.setText("Productos");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(this::jButton4jButtonProductos);

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/masa.png"))); // NOI18N
        jButton5.setText("Producción");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.addActionListener(this::jButton5jButtonProduccion);

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/requisicion.png"))); // NOI18N
        jButton6.setText("Requisiciones");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(this::jButton6jButtonRequisiciones);

        BtnTarjetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        BtnTarjetaTiempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        BtnTarjetaTiempo.setText("Tarjeta Tiempo");
        BtnTarjetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnTarjetaTiempo.addActionListener(this::BtnTarjetaTiempojButtonReporte);

        jButton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/cerrar-sesion.png"))); // NOI18N
        jButton8.setText("Cerrar Sesión");
        jButton8.addActionListener(this::jButton8jButtonCerrarSesion);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/LogoCorrecto.png"))); // NOI18N

        HojaCostos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HojaCostos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/reportes.png"))); // NOI18N
        HojaCostos.setText("Hoja Costos");
        HojaCostos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HojaCostos.addActionListener(this::HojaCostosjButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnTarjetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HojaCostos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 242, 242));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 28)); // NOI18N
        jLabel1.setText("Requisición de materiales");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Datos de la Requisición");

        jLabel3.setText("No. Requisición:");

        txtNoRequisicion.setEditable(false);

        jLabel4.setText("Fecha:");

        txtFechaReq.setToolTipText("yyyy-MM-dd");

        jLabel5.setText("Departamento:");

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        cmbDepartamento.addActionListener(this::cmbDepartamentoActionPerformed);

        jLabel6.setText("Solicitante:");

        jLabel7.setText("No. Pedido:");

        jLabel8.setText("Observaciones:");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        cmbNoPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cmbSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNoRequisicion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbNoPedidos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFechaReq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cmbSolicitante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoRequisicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNoPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Detalle de materiales solicitados");

        tblMaterialesSolicitados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Material/Ingrediente", "Unidad", "Cantidad", "Costo Unitario", "Total"
            }
        ));
        jScrollPane2.setViewportView(tblMaterialesSolicitados);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("TOTAL:");

        txtTotalReq.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(33, 33, 33)
                        .addComponent(txtTotalReq, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTotalReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Firmas");

        jLabel18.setText("Entregado por:");

        jLabel19.setText("Recibido por:");

        buttonGenerarReqActionPerformed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonGenerarReqActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/editar.png"))); // NOI18N
        buttonGenerarReqActionPerformed.setText("Generar Requisición");
        buttonGenerarReqActionPerformed.addActionListener(this::buttonGenerarReqActionPerformedActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(buttonGenerarReqActionPerformed)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonGenerarReqActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Lista de Requisiciones de Materiales");

        tblRequisiciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Requisición", "Fecha", "Departamento", "No. Pedido", "Solicitante", "Materiales", "Total", "Estado", "Entregado por", "Recibido por"
            }
        ));
        tblRequisiciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRequisicionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblRequisiciones);

        ImprimirReq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ImprimirReq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/imprimir.png"))); // NOI18N
        ImprimirReq.setText("Imprimir");
        ImprimirReq.addActionListener(this::ImprimirReqActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ImprimirReq, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ImprimirReq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Recursos/guardar.png"))); // NOI18N
        jButton17.setText("Guardar");
        jButton17.addActionListener(this::BtnGuardarReq);

        ButtonEliminarActionPerformed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonEliminarActionPerformed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/borrar.png"))); // NOI18N
        ButtonEliminarActionPerformed.setText("Eliminar");
        ButtonEliminarActionPerformed.addActionListener(this::ButtonEliminarActionPerformedActionPerformed);

        ButtonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/limpiar.png"))); // NOI18N
        ButtonLimpiar.setText("Limpiar");
        ButtonLimpiar.addActionListener(this::ButtonLimpiarActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(188, 188, 188)
                                .addComponent(ButtonEliminarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187)
                                .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEliminarActionPerformed, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarReq(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarReq
        // TODO add your handling code here:
       try{

        Requisicion req = new Requisicion();

        String departamento =
                cmbDepartamento.getSelectedItem().toString();

        RequisicionDAO dao =
                new RequisicionDAO();

        int idDepartamento =
                dao.obtenerIdDepartamento(departamento);

        req.setIdDepartamento(idDepartamento);

        SimpleDateFormat formato =
                new SimpleDateFormat("yyyy-MM-dd");

        req.setFecha(
                formato.parse(
                        txtFechaReq.getText()));

        String pedido =
                cmbNoPedidos.getSelectedItem().toString();

        int idPedido =
                Integer.parseInt(
                        pedido.split(" - ")[0]);

        req.setIdPedido(idPedido);

        req.setSolicitante(
                cmbSolicitante.getSelectedItem().toString());

        req.setObservaciones(
                txtObservaciones.getText());

        req.setTotal(
                Double.parseDouble(
                        txtTotalReq.getText()));

        req.setEntregadoPor(
                txtEntrega.getText());

        req.setRecibidoPor(
                txtRecibido.getText());

        // VALIDAR INVENTARIO ANTES DE GUARDAR

        DefaultTableModel modelo =
                (DefaultTableModel)
                tblMaterialesSolicitados.getModel();

            for(int i = 0;
                i < modelo.getRowCount();
                i++){

                String ingrediente =
                        modelo.getValueAt(i, 1)
                        .toString();

                int idIngrediente =
                        dao.obtenerIdIngrediente(
                                ingrediente);

                double cantidad =
                        Double.parseDouble(
                                modelo.getValueAt(i, 3)
                                .toString());

                if(!dao.verificarExistencia(
                        idIngrediente,
                        cantidad)){

                    JOptionPane.showMessageDialog(
                            this,
                            "Inventario insuficiente para: "
                            + ingrediente);

                    return;
                }

            }

            // GUARDAR REQUISICIÓN

            int idRequisicion =
                    dao.guardarRequisicion(req);

            if(idRequisicion > 0){

                // GUARDAR DETALLE Y DESCONTAR INVENTARIO

                for(int i = 0;
                    i < modelo.getRowCount();
                    i++){

                    String ingrediente =
                            modelo.getValueAt(i, 1)
                            .toString();

                    int idIngrediente =
                            dao.obtenerIdIngrediente(
                                    ingrediente);

                    double cantidad =
                            Double.parseDouble(
                                    modelo.getValueAt(i, 3)
                                    .toString());

                    double costoUnitario =
                            Double.parseDouble(
                                    modelo.getValueAt(i, 4)
                                    .toString());

                    double total =
                            Double.parseDouble(
                                    modelo.getValueAt(i, 5)
                                    .toString());

                    dao.guardarDetalleRequisicion(
                            idRequisicion,
                            idIngrediente,
                            cantidad,
                            costoUnitario,
                            total);

                    dao.descontarInventario(
                            idIngrediente,
                            cantidad);

                }

                JOptionPane.showMessageDialog(
                        this,
                        "Requisición guardada correctamente");

                dao.mostrarRequisiciones(
                        tblRequisiciones);

            }else{

            JOptionPane.showMessageDialog(this,"Error al guardar la requisición");

            }

        }catch(Exception e){

        System.out.println("Error: " + e);

        }
        
    }//GEN-LAST:event_BtnGuardarReq

    private void buttonGenerarReqActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarReqActionPerformedActionPerformed
        // TODO add your handling code here:
        String pedido =cmbNoPedidos.getSelectedItem().toString();

        int idPedido =Integer.parseInt(pedido.split(" - ")[0]);
        
        RequisicionDAO dao = new RequisicionDAO();
        dao.mostrarMaterialesSolicitados(tblMaterialesSolicitados, idPedido);
        
        calcularTotalRequisicion();
    }//GEN-LAST:event_buttonGenerarReqActionPerformedActionPerformed

    private void ButtonEliminarActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformedActionPerformed
        // TODO add your handling code here:
       if(txtNoRequisicion.getText().equals("")){

        JOptionPane.showMessageDialog(this,"Selecciona una requisición");

        return;

        }

        int confirmar =JOptionPane.showConfirmDialog( this,
                "¿Deseas eliminar esta requisición?", "Confirmar",JOptionPane.YES_NO_OPTION);

        if(confirmar != JOptionPane.YES_OPTION){

            return;

        }

        RequisicionDAO dao = new RequisicionDAO();

        boolean respuesta = dao.eliminarRequisicion(Integer.parseInt(txtNoRequisicion.getText()));

        if(respuesta){

            JOptionPane.showMessageDialog(this,"Requisición eliminada");

            dao.mostrarRequisiciones(tblRequisiciones);

            limpiar();

        }else{

            JOptionPane.showMessageDialog(this,"Error al eliminar");

        }

    }//GEN-LAST:event_ButtonEliminarActionPerformedActionPerformed

    private void ButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_ButtonLimpiarActionPerformed

    private void cmbDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartamentoActionPerformed
        // TODO add your handling code here:
        if(cmbDepartamento.getSelectedItem() == null){

        return;

        }

        String departamento =cmbDepartamento.getSelectedItem().toString();

        RequisicionDAO dao = new RequisicionDAO();

        dao.llenarSolicitantes(cmbSolicitante, departamento);
    }//GEN-LAST:event_cmbDepartamentoActionPerformed

    private void tblRequisicionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRequisicionesMouseClicked
        // TODO add your handling code here:
        int fila = tblRequisiciones.getSelectedRow();

        txtNoRequisicion.setText( tblRequisiciones.getValueAt(
                        fila, 0).toString());

        txtFechaReq.setText( tblRequisiciones.getValueAt(
                        fila, 1).toString());

        cmbDepartamento.setSelectedItem( tblRequisiciones.getValueAt(
                        fila, 2).toString());

        cmbSolicitante.setSelectedItem( tblRequisiciones.getValueAt(
                        fila, 3).toString());

        txtTotalReq.setText( tblRequisiciones.getValueAt(
                        fila, 5).toString());
        
        int idRequisicion =Integer.parseInt(txtNoRequisicion.getText());

        RequisicionDAO dao =new RequisicionDAO();

        dao.mostrarDetalleRequisicion(tblMaterialesSolicitados,idRequisicion);
    }//GEN-LAST:event_tblRequisicionesMouseClicked

    private void ImprimirReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirReqActionPerformed
        // TODO add your handling code here:
        if(txtNoRequisicion.getText().equals("")){

            JOptionPane.showMessageDialog( this, "Selecciona una requisición");

            return;
        }
        
        JTextArea reporte = new JTextArea();
        
        reporte.append("PASTELERIA\n\n");

        reporte.append("REQUISICION DE MATERIALES\n\n");

        reporte.append("No. Requisicion: " + txtNoRequisicion.getText() + "\n");

        reporte.append("Fecha: " + txtFechaReq.getText() + "\n\n");

        reporte.append("Departamento: " + cmbDepartamento.getSelectedItem() + "\n");

        reporte.append("Solicitante: " + cmbSolicitante.getSelectedItem() + "\n\n");
        
        DefaultTableModel modelo =
        (DefaultTableModel)
        tblMaterialesSolicitados.getModel();

        reporte.append("Cant.    Ingrediente         C.Unit.     Total\n");

        reporte.append("------------------------------------------------\n");

        for(int i = 0;
            i < modelo.getRowCount();
            i++){

            reporte.append(
                modelo.getValueAt(i, 3) + "\t"
                + modelo.getValueAt(i, 1) + "\t"
                + modelo.getValueAt(i, 4) + "\t"
                + modelo.getValueAt(i, 5)
                + "\n");

        }
        
        reporte.append(
        "\n---------------------------------\n");

        reporte.append("TOTAL: $"  + txtTotalReq.getText() + "\n\n");

        reporte.append( "Entregado por: " + txtEntrega.getText() + "\n");

        reporte.append( "Recibido por: " + txtRecibido.getText() + "\n");
        
        try{

            reporte.print();

        }catch(Exception e){

            System.out.println(
                    "Error: " + e);

        }
    }//GEN-LAST:event_ImprimirReqActionPerformed

    private void jButton1MenuInicioButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1MenuInicioButton
        // TODO add your handling code here:
        FrmMenuInicio menuInicio = new FrmMenuInicio();
        menuInicio.setVisible(true);
    }//GEN-LAST:event_jButton1MenuInicioButton

    private void jButton2jButtonEmpleados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2jButtonEmpleados
        // TODO add your handling code here:
        if(Sesion.idDepartamento != 4){

            JOptionPane.showMessageDialog(
                    this,
                    "Solo el departamento Administrador puede acceder al módulo de empleados.");

            return;

        }

        FrmEmpleado frm =
                new FrmEmpleado();

        frm.setVisible(true);
    }//GEN-LAST:event_jButton2jButtonEmpleados

    private void jButton3jButtonInventario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3jButtonInventario
        // TODO add your handling code here:
        FrmInventario inventario = new FrmInventario();
        inventario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3jButtonInventario

    private void jButton4jButtonProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButtonProductos
        // TODO add your handling code here:
        FrmProducto producto = new FrmProducto();
        producto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4jButtonProductos

    private void jButton5jButtonProduccion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5jButtonProduccion
        // TODO add your handling code here:
        FrmProduccion produccion = new FrmProduccion();
        produccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5jButtonProduccion

    private void jButton6jButtonRequisiciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6jButtonRequisiciones
        // TODO add your handling code here:
        FrmRequisicion req = new FrmRequisicion();
        req.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6jButtonRequisiciones

    private void BtnTarjetaTiempojButtonReporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTarjetaTiempojButtonReporte
        // TODO add your handling code here:
        FrmTarjetaTiempo tarjeta = new FrmTarjetaTiempo();
        tarjeta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnTarjetaTiempojButtonReporte

    private void jButton8jButtonCerrarSesion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButtonCerrarSesion
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(
            this,
            "¿Estas seguro de Cerrar Sesión?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

        if(opcion == JOptionPane.YES_OPTION){

            FrmLogin login = new FrmLogin();
            login.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton8jButtonCerrarSesion

    private void HojaCostosjButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HojaCostosjButton
        // TODO add your handling code here:
        FrmHojaCostos hojaCostos = new FrmHojaCostos();
        hojaCostos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HojaCostosjButton

    
    public void calcularTotalRequisicion(){

        double total = 0;

        DefaultTableModel modelo =(DefaultTableModel) tblMaterialesSolicitados.getModel();

        for(int i = 0;i < modelo.getRowCount(); i++){

            total += Double.parseDouble(modelo.getValueAt(i, 5).toString());

        }

        txtTotalReq.setText(String.valueOf(total));

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRequisicion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTarjetaTiempo;
    private javax.swing.JButton ButtonEliminarActionPerformed;
    private javax.swing.JButton ButtonLimpiar;
    private javax.swing.JButton HojaCostos;
    private javax.swing.JButton ImprimirReq;
    private javax.swing.JButton buttonGenerarReqActionPerformed;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbNoPedidos;
    private javax.swing.JComboBox<String> cmbSolicitante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblMaterialesSolicitados;
    private javax.swing.JTable tblRequisiciones;
    private javax.swing.JTextField txtEntrega;
    private javax.swing.JTextField txtFechaReq;
    private javax.swing.JTextField txtNoRequisicion;
    private javax.swing.JTextArea txtObservaciones;
    private javax.swing.JTextField txtRecibido;
    private javax.swing.JTextField txtTotalReq;
    // End of variables declaration//GEN-END:variables
}
